version: '3'
services:
  reverseproxy:
    build:
      context: ./
    image: heniam/reverse-proxy
  backend-user:
    build:
      context: ../../api-user
    image: heniam/udagram-api-user
  backend-feed:
    build:
      context: ../../api-feed
    image: heniam/udagram-api-feed
  front-end:
    build:
      context: ../../frontend
    image: heniam/udagram-frontend